export const about = {
  'about.hero.greeting':   { en: 'Hi, my name is',          es: 'Hola, mi nombre es' },
  'about.hero.tagline':    { en: 'I engineer biology for a better future.', es: 'Hago ingeniería biológica para un futuro mejor.' },
  'about.hero.bio':        { en: 'I am an Associate Professor at Universidad de los Andes, leading research at the convergence of biotechnology, nanotechnology, and AI to transform complex challenges into sustainable, high-impact solutions.', es: 'Soy Profesor Asociado en la Universidad de los Andes, liderando investigación en la convergencia de biotecnología, nanotecnología e IA para transformar desafíos complejos en soluciones sostenibles de alto impacto.' },
  'about.hero.cta':        { en: 'Explore My Work',          es: 'Explorar mi trabajo' },
  'about.purpose.title':   { en: 'My Professional Purpose',  es: 'Mi Propósito Profesional' },
  'about.purpose.text':    { en: 'I am dedicated to driving innovation in biotechnology, nanotechnology, and generative AI. My professional purpose is to transform complex challenges into practical solutions that enhance quality of life and promote sustainable development.', es: 'Me dedico a impulsar la innovación en biotecnología, nanotecnología e IA generativa. Mi propósito profesional es transformar desafíos complejos en soluciones prácticas que mejoren la calidad de vida y promuevan el desarrollo sostenible.' },
  'about.mission.title':   { en: 'Mission & Approach',       es: 'Misión y Enfoque' },
  'about.mission.researchers.title': { en: 'For Researchers & Academics', es: 'Para Investigadores y Académicos' },
  'about.mission.researchers.text':  { en: 'Leading and collaborating on applied, interdisciplinary research projects that address real-world problems.', es: 'Liderando y colaborando en proyectos de investigación aplicada e interdisciplinaria que abordan problemas del mundo real.' },
  'about.mission.students.title': { en: 'For Engineering Students', es: 'Para Estudiantes de Ingeniería' },
  'about.mission.students.text':  { en: 'Providing mentorship and specialized training to deepen knowledge and foster the next generation of innovators.', es: 'Brindando mentoría y formación especializada para profundizar el conocimiento y cultivar la próxima generación de innovadores.' },
  'about.mission.industry.title': { en: 'For Companies & Startups', es: 'Para Empresas y Startups' },
  'about.mission.industry.text':  { en: 'Advising on the implementation of advanced technologies to improve processes, products, and solutions.', es: 'Asesorando en la implementación de tecnologías avanzadas para mejorar procesos, productos y soluciones.' },
  'about.education.title': { en: 'Academic Background',      es: 'Formación Académica' },
  'about.experience.title': { en: 'Work Experience',         es: 'Experiencia Laboral' },
  'about.continuing.title': { en: 'Continuing Education & Specializations', es: 'Educación Continua y Especializaciones' },
  'about.licenses.title':  { en: 'Licenses & Certifications', es: 'Licencias y Certificaciones' },
  'about.collab.title':    { en: "Let's Collaborate",         es: 'Colaboremos' },
  'about.collab.text':     { en: 'I am always looking to connect with professionals and organizations that share my passion for technological innovation. If you are looking for collaboration or expert advice in biotechnology, nanotechnology, or generative AI, feel free to reach out. I am here to help turn your ideas into tangible realities.', es: 'Siempre estoy buscando conectar con profesionales y organizaciones que compartan mi pasión por la innovación tecnológica. Si buscas colaboración o asesoría experta en biotecnología, nanotecnología o IA generativa, no dudes en escribirme. Estoy aquí para ayudar a convertir tus ideas en realidades tangibles.' },
  'about.collab.cta':      { en: 'Get in Touch',              es: 'Escríbeme' },
} as const;
