export const nav = {
  'nav.principles':        { en: 'Guiding Principles',      es: 'Principios Rectores' },
  'nav.principles.teaching': { en: 'Teaching Purpose',      es: 'Propósito Docente' },
  'nav.principles.research': { en: 'Research Purpose',      es: 'Propósito Investigador' },
  'nav.principles.service':  { en: 'Service Purpose',       es: 'Propósito de Servicio' },
  'nav.principles.philosophy': { en: 'Teaching Philosophy', es: 'Filosofía de Enseñanza' },
  'nav.research':          { en: 'Research',                es: 'Investigación' },
  'nav.research.overview': { en: 'Overview',                es: 'Visión General' },
  'nav.research.program':  { en: 'Research Program',        es: 'Programa de Investigación' },
  'nav.research.products': { en: 'Products',                es: 'Productos' },
  'nav.research.grants':   { en: 'Grants',                  es: 'Financiamiento' },
  'nav.research.students': { en: 'Grad Students',           es: 'Estudiantes de Posgrado' },
  'nav.teaching':          { en: 'Teaching',                es: 'Docencia' },
  'nav.teaching.overview': { en: 'Overview',                es: 'Visión General' },
  'nav.teaching.courses':  { en: 'Courses Taught',          es: 'Cursos Impartidos' },
  'nav.teaching.unitops':  { en: 'Unit Ops Innovation',     es: 'Innovación en Ops. Unitarias' },
  'nav.teaching.continuing': { en: 'Continuing Education',  es: 'Educación Continua' },
  'nav.teaching.testimonials': { en: 'Testimonials',        es: 'Testimonios' },
  'nav.teaching.scholarship':  { en: 'Scholarship of Teaching', es: 'Investigación Pedagógica (SoTL)' },
  'nav.teaching.profdev':  { en: 'Professional Development', es: 'Desarrollo Profesional' },
  'nav.service':           { en: 'Service',                 es: 'Servicio' },
  'nav.service.overview':  { en: 'Overview',                es: 'Visión General' },
  'nav.service.ai':        { en: 'Augmented Intelligence',  es: 'Inteligencia Aumentada' },
  'nav.service.leadership': { en: 'Service & Leadership',   es: 'Servicio y Liderazgo' },
  'nav.service.editorial': { en: 'Editorial Boards',        es: 'Comités Editoriales' },
  'nav.service.outreach':  { en: 'Outreach & Scouting',     es: 'Divulgación y Scouting' },
  'nav.recognition':       { en: 'Recognition',             es: 'Reconocimientos' },
  'nav.classroom':         { en: 'Classroom',               es: 'Aula' },
  'nav.downloadCv':        { en: 'Download CV',             es: 'Descargar CV' },
} as const;
