export const teaching = {
  // Teaching Overview
  'teaching.overview.title':    { en: 'Teaching Overview',  es: 'Visión General de Docencia' },
  'teaching.overview.subtitle': { en: 'Fostering the next generation of innovators through project-based learning and real-world challenges.', es: 'Formando a la próxima generación de innovadores mediante aprendizaje basado en proyectos y retos del mundo real.' },
  'teaching.overview.approach.title': { en: 'My Teaching Approach', es: 'Mi Enfoque Pedagógico' },
  'teaching.overview.approach.text':  { en: 'My teaching portfolio reflects a deep commitment to engineering education across all levels, from core undergraduate courses to specialized graduate seminars and professional development programs. My courses are designed to be dynamic, hands-on learning environments where students tackle real-world challenges. I emphasize a project-based approach that not only builds strong technical foundations but also cultivates essential professional skills like critical thinking, teamwork, and communication. Through my involvement in curriculum design, continuing education, and corporate training, I strive to create impactful learning experiences that bridge the gap between academic theory and industry practice, empowering the next generation of engineers to innovate and lead.', es: 'Mi portafolio docente refleja un profundo compromiso con la educación en ingeniería en todos los niveles, desde cursos básicos de pregrado hasta seminarios especializados de posgrado y programas de desarrollo profesional. Mis cursos están diseñados como entornos de aprendizaje dinámicos y prácticos donde los estudiantes abordan desafíos del mundo real. Hago énfasis en un enfoque basado en proyectos que no solo construye fundamentos técnicos sólidos, sino que también cultiva habilidades profesionales esenciales como el pensamiento crítico, el trabajo en equipo y la comunicación. A través de mi participación en el diseño curricular, la educación continua y la formación corporativa, me esfuerzo por crear experiencias de aprendizaje que cierren la brecha entre la teoría académica y la práctica industrial, empoderando a la próxima generación de ingenieros para innovar y liderar.' },

  // Courses
  'courses.title':           { en: 'Courses Taught',         es: 'Cursos Impartidos' },
  'courses.sub':             { en: 'Below is a comprehensive list of courses I have taught since 2017, detailing student engagement, course type, and my role in their design.', es: 'A continuación se presenta una lista completa de los cursos que he impartido desde 2017, con detalle de la participación estudiantil, el tipo de curso y mi rol en su diseño.' },
  'courses.col.term':        { en: 'Term',                   es: 'Período' },
  'courses.col.course':      { en: 'Course',                 es: 'Curso' },
  'courses.col.students':    { en: 'Students',               es: 'Estudiantes' },
  'courses.col.type':        { en: 'Type',                   es: 'Tipo' },
  'courses.col.evaluation':  { en: 'Student Evaluation',     es: 'Evaluación Estudiantil' },
  'courses.filter.all':         { en: 'All',           es: 'Todos' },
  'courses.filter.core':        { en: 'Core',          es: 'Obligatorio' },
  'courses.filter.elective':    { en: 'Elective',      es: 'Electivo' },
  'courses.filter.cbu':         { en: 'CBU',           es: 'CBU' },
  'courses.filter.undergraduate': { en: 'Undergraduate', es: 'Pregrado' },
  'courses.filter.graduate':    { en: 'Graduate',      es: 'Posgrado' },

  // Unit Ops Innovation
  'unitops.title':           { en: 'Unit Operations Innovation', es: 'Innovación en Operaciones Unitarias' },
  'unitops.sub':             { en: 'A Seven-Year Journey: From Theory and Problem-Sets to Project-Based Synthesis.', es: 'Un recorrido de siete años: de la teoría y los ejercicios al aprendizaje basado en proyectos.' },
  'unitops.context':         { en: 'Context',                es: 'Contexto' },
  'unitops.evolution':       { en: 'The Evolution',          es: 'La Evolución' },
  'unitops.impact':          { en: 'Impact on Student Experience', es: 'Impacto en la Experiencia Estudiantil' },
  'unitops.lessons':         { en: 'Lessons Learned',        es: 'Lecciones Aprendidas' },
  'unitops.scholarly':       { en: 'Scholarly Foundation',   es: 'Base Académica' },
  'unitops.chart.title':     { en: 'Score Evolution: The Reform Journey', es: 'Evolución de Puntajes: El Camino de la Reforma' },
  'unitops.chart.scale':     { en: 'Institutional 100–200 Scale', es: 'Escala Institucional 100–200' },
  'unitops.phase.traditional': { en: 'Traditional',         es: 'Tradicional' },
  'unitops.phase.reform':    { en: 'Reform Era',             es: 'Era de Reforma' },
  'unitops.phase.synthesis': { en: 'Synthesis',              es: 'Síntesis' },
  'unitops.quote':           { en: '"The result speaks for itself. The course now combines the rigor students expect with the authentic design experience that motivated the original transformation."', es: '«El resultado habla por sí solo. El curso ahora combina el rigor que los estudiantes esperan con la experiencia auténtica de diseño que motivó la transformación original.»' },
  'unitops.context.text1':   { en: 'Unit Operations is the foundational course in chemical engineering curricula worldwide. In 2021, at the suggestion of the ', es: 'Operaciones Unitarias es el curso fundamental en los planes de estudio de ingeniería química en todo el mundo. En 2021, por sugerencia de la ' },
  'unitops.context.school':  { en: 'School of Engineering', es: 'Facultad de Ingeniería' },
  'unitops.context.text2':   { en: ' to strengthen experiential learning, the ', es: ' de fortalecer el aprendizaje experiencial, el ' },
  'unitops.context.dept':    { en: 'Department of Chemical and Food Engineering', es: 'Departamento de Ingeniería Química y de Alimentos' },
  'unitops.context.text3':   { en: ' decided to take on a comprehensive curriculum reform. This documentation chronicles the transformation of Unit Operations under that reform, the challenges encountered, and the pedagogical synthesis that eventually emerged.', es: ' decidió emprender una reforma curricular integral. Esta documentación narra la transformación de Operaciones Unitarias bajo esa reforma, los desafíos enfrentados y la síntesis pedagógica que finalmente surgió.' },
  'unitops.phase1.title':    { en: 'Phase 1: Traditional Approach (2017–2021)', es: 'Fase 1: Enfoque Tradicional (2017–2021)' },
  'unitops.phase1.tag':      { en: 'Stable',                 es: 'Estable' },
  'unitops.phase1.textPre':  { en: 'The original course followed the standard model: comprehensive lectures covering theoretical foundations, worked examples, and traditional homework assignments. Evaluations were stable, averaging ', es: 'El curso original seguía el modelo estándar: clases magistrales completas que cubrían los fundamentos teóricos, ejemplos resueltos y tareas tradicionales. Las evaluaciones eran estables, con un promedio de ' },
  'unitops.phase1.textPost': { en: '. While effective, the format offered limited opportunity for students to integrate concepts through authentic engineering problems.', es: '. Aunque efectivo, el formato ofrecía pocas oportunidades para que los estudiantes integraran conceptos mediante problemas auténticos de ingeniería.' },
  'unitops.phase2.title':    { en: 'Phase 2: Curriculum Reform and PO-PBL (2021–2023)', es: 'Fase 2: Reforma Curricular y PO-PBL (2021–2023)' },
  'unitops.phase2.tag':      { en: 'Declined',               es: 'En Declive' },
  'unitops.phase2.text1':    { en: 'The course became {ip2} under a pure Project-Oriented Problem-Based Learning format. Theory was minimized as students learned through semester-long design projects.', es: 'El curso se convirtió en {ip2} bajo un formato puro de Aprendizaje Basado en Problemas Orientado a Proyectos. La teoría se minimizó a medida que los estudiantes aprendían mediante proyectos de diseño a lo largo del semestre.' },
  'unitops.phase2.ip2':      { en: 'Integrated Project 2',   es: 'Proyecto Integrador 2' },
  'unitops.phase2.text2pre': { en: 'The magnitude of change was severe. Student response was challenging; evaluations dropped sharply to a ', es: 'La magnitud del cambio fue severa. La respuesta de los estudiantes fue difícil; las evaluaciones cayeron bruscamente hasta un ' },
  'unitops.phase2.lowOf':    { en: 'low of ',               es: 'mínimo de ' },
  'unitops.phase2.lowIn':    { en: 'in',                    es: 'en' },
  'unitops.phase2.text2post':{ en: '. Students expressed frustration with the cognitive load of learning new concepts while simultaneously applying them without structured theoretical guidance.', es: '. Los estudiantes expresaron frustración por la carga cognitiva de aprender conceptos nuevos y aplicarlos simultáneamente sin una guía teórica estructurada.' },
  'unitops.phase3.title':    { en: 'Phase 3: Finding the Balance (2024–Present)', es: 'Fase 3: Encontrando el Equilibrio (2024–Presente)' },
  'unitops.phase3.tag':      { en: 'Recovered',              es: 'Recuperado' },
  'unitops.phase3.text1':    { en: 'The transition to Unit Operations Project in 2024 marked a new synthesis. I integrated ', es: 'La transición a Proyecto de Operaciones Unitarias en 2024 marcó una nueva síntesis. Integré ' },
  'unitops.phase3.genai':    { en: 'Generative AI',          es: 'IA Generativa' },
  'unitops.phase3.text2':    { en: ' tools and added theoretical content back. The final breakthrough came in 2025-20 with a deliberate ', es: ' y volví a añadir contenido teórico. El avance definitivo llegó en 2025-20 con una estructura deliberada ' },
  'unitops.phase3.fifty':    { en: '50-50 structure',        es: '50-50' },
  'unitops.phase3.text3':    { en: ': half dedicated to theory and problem-solving, and half to a semester-long ', es: ': la mitad dedicada a la teoría y la resolución de problemas, y la mitad a un proyecto de diseño ' },
  'unitops.phase3.insilico': { en: 'in silico',              es: 'in silico' },
  'unitops.phase3.text4':    { en: ' design project using ',   es: ' a lo largo del semestre usando ' },
  'unitops.phase3.aspen':    { en: 'ASPEN simulation',       es: 'simulación en ASPEN' },
  'unitops.phase3.text5':    { en: '. Evaluations recovered to ', es: '. Las evaluaciones se recuperaron hasta ' },
  'unitops.phase3.text5b':   { en: ' in ',                   es: ' en ' },
  'unitops.phase3.text5c':   { en: ' and have held there since: ', es: ' y se han sostenido desde entonces: ' },
  'unitops.phase3.text6':    { en: ' \u2014 above the ',        es: ', por encima del promedio de ' },
  'unitops.phase3.text7':    { en: ' average of the years before the reform.', es: ' de los años previos a la reforma.' },
  'unitops.chart.notePre':   { en: "Note: Pandora's Laboratory maintained a consistent ", es: 'Nota: el Laboratorio de Pandora mantuvo un promedio constante de ' },
  'unitops.chart.notePost':  { en: ' average as a reference benchmark across the same period.', es: ' como referente durante el mismo período.' },
  'unitops.chart.benchmark': { en: 'Ref Benchmark',          es: 'Referente' },
  'unitops.lesson1.title':   { en: 'Theoretical Foundations', es: 'Fundamentos Teóricos' },
  'unitops.lesson1.desc':    { en: 'Even in project-based contexts, students value theoretical frameworks. Explicit instruction provides the scaffolding needed to tackle complex problems confidently.', es: 'Incluso en contextos basados en proyectos, los estudiantes valoran los marcos teóricos. La instrucción explícita brinda el andamiaje necesario para abordar problemas complejos con confianza.' },
  'unitops.lesson2.title':   { en: 'Iterative Refinement',   es: 'Refinamiento Iterativo' },
  'unitops.lesson2.descPre': { en: 'Pedagogical innovation requires sustaining and documenting each phase. The evaluation recovery from ', es: 'La innovación pedagógica requiere sostener y documentar cada fase. La recuperación de las evaluaciones de ' },
  'unitops.lesson2.descTo':  { en: ' to ',                   es: ' a ' },
  'unitops.lesson2.descOver':{ en: ' occurred over ',        es: ' ocurrió a lo largo de ' },
  'unitops.lesson2.descPost':{ en: ' semesters of sustainment.', es: ' semestres de sostenimiento.' },
  'unitops.lesson3.title':   { en: 'In Silico Bridging',     es: 'Puente In Silico' },
  'unitops.lesson3.desc':    { en: 'ASPEN simulation addresses physical laboratory constraints, allowing students to see immediate consequences of engineering decisions in larger scopes.', es: 'La simulación en ASPEN aborda las limitaciones del laboratorio físico, permitiendo a los estudiantes ver las consecuencias inmediatas de las decisiones de ingeniería en escalas mayores.' },
  'unitops.lesson4.title':   { en: 'AI-Assisted Rigor',      es: 'Rigor Asistido por IA' },
  'unitops.sotlLink':        { en: 'This course is one case in a longer practice of studying my own teaching.', es: 'Este curso es un caso dentro de una práctica más larga de estudiar mi propia docencia.' },
  'unitops.sotlLinkCta':     { en: 'Scholarship of Teaching & Learning', es: 'Investigación Pedagógica (SoTL)' },
  'unitops.award.eyebrow':   { en: 'AIChE Education Division · 2026', es: 'División de Educación de AIChE · 2026' },
  'unitops.award.title':     { en: 'Award for Innovation in Chemical Engineering Education', es: 'Award for Innovation in Chemical Engineering Education' },
  'unitops.award.citation':  { en: '«For integrating generative AI into chemical engineering education through the Cognitive-AI Synergy Framework and a project-based Unit Operations model with measurable impact on student learning.»', es: '«Por integrar la IA generativa en la educación en ingeniería química a través del Cognitive-AI Synergy Framework y un modelo de Operaciones Unitarias basado en proyectos, con impacto medible en el aprendizaje de los estudiantes.»' },
  'unitops.award.note':      { en: 'The American Institute of Chemical Engineers recognized the work this page documents. Since the award was created it had never gone outside the United States.', es: 'El American Institute of Chemical Engineers reconoció el trabajo que documenta esta página. Desde la creación del premio nunca había salido de Estados Unidos.' },
  'unitops.award.cta':       { en: 'See the recognition', es: 'Ver el reconocimiento' },
  'unitops.award.ctaAiche':  { en: 'Award at AIChE', es: 'El premio en AIChE' },
  'unitops.lesson4.desc':    { en: 'GenAI tools support learning when properly scaffolded. Structured AI integration (AIAS framework) improved literature review quality while maintaining rigor.', es: 'Las herramientas de IA generativa apoyan el aprendizaje cuando se andamian adecuadamente. La integración estructurada de IA (marco AIAS) mejoró la calidad de las revisiones de literatura manteniendo el rigor.' },

  // Continuing Education
  'contEd.title':            { en: 'Continuing Education',   es: 'Educación Continua' },
  'contEd.sub':              { en: 'Beyond traditional university courses, I am actively involved in designing and delivering continuing education programs and corporate training. These courses aim to bridge the gap between academia and industry, providing professionals with cutting-edge skills in areas like artificial intelligence, biotechnology, and innovation management.', es: 'Más allá de los cursos universitarios tradicionales, participo activamente en el diseño y la impartición de programas de educación continua y formación corporativa. Estos cursos buscan cerrar la brecha entre la academia y la industria, dotando a los profesionales de habilidades de vanguardia en áreas como inteligencia artificial, biotecnología y gestión de la innovación.' },
  'contEd.col.year':         { en: 'Year',                   es: 'Año' },
  'contEd.col.title':        { en: 'Course Title',           es: 'Título del Curso' },
  'contEd.col.type':         { en: 'Type / Client',          es: 'Tipo / Cliente' },
  'contEd.col.attendees':    { en: 'Attendees',              es: 'Participantes' },
  'contEd.col.role':         { en: 'Role',                   es: 'Rol' },
  'contEd.filter.all':         { en: 'All',              es: 'Todos' },
  'contEd.filter.open':        { en: 'Open Course',      es: 'Curso Abierto' },
  'contEd.filter.corporate':   { en: 'Corporate Course', es: 'Curso Corporativo' },
  'contEd.filter.summer':      { en: 'Summer School',    es: 'Escuela de Verano' },

  // Testimonials
  'testimonials.title':      { en: 'Student Testimonials',   es: 'Testimonios de Estudiantes' },
  'testimonials.sub':        { en: 'Hearing from students is the most meaningful measure of teaching success. Here is what some of my past and present students have to say about their learning experiences.', es: 'Escuchar a los estudiantes es la medida más significativa del éxito docente. Esto es lo que algunos de mis estudiantes, pasados y presentes, tienen que decir sobre sus experiencias de aprendizaje.' },
  'testimonials.filter.all': { en: 'All',                    es: 'Todos' },
  'testimonials.filter.teaching': { en: 'Teaching & Mentorship', es: 'Docencia y Mentoría' },
  'testimonials.filter.research': { en: 'Research Advising', es: 'Asesoría de Investigación' },

  // Scholarship of Teaching
  'sotl.title':              { en: 'Scholarship of Teaching & Learning (SOTL)', es: 'Investigación sobre la Enseñanza y el Aprendizaje (SoTL)' },
  'sotl.sub':                { en: 'I study my own courses. Each redesign is an intervention with a baseline, an instrument, successive cohorts, and a result that goes through peer review before it changes how I teach.', es: 'Estudio mis propios cursos. Cada rediseño es una intervención con línea base, instrumento, cohortes sucesivas y un resultado que pasa por revisión por pares antes de cambiar mi manera de enseñar.' },
  'sotl.editorial':          { en: 'Editorial Contributions', es: 'Contribuciones Editoriales' },
  'sotl.publications':       { en: 'Related Publications',   es: 'Publicaciones Relacionadas' },
  'sotl.visitJournal':       { en: 'Visit Journal',          es: 'Visitar Revista' },
  'sotl.readMore':           { en: 'Read More →',            es: 'Leer más →' },
  'sotl.intro1':             { en: 'Teaching generates data. I collect it and subject it to the same methods I use in the laboratory: a baseline, an intervention, cohorts compared under one instrument, and independent evaluation when the outcome depends on judgment. The Project of Unit Operations has been my main object of study since 2017.', es: 'La docencia genera datos. Los recojo y los someto a los mismos métodos que uso en el laboratorio: una línea base, una intervención, cohortes comparadas bajo un mismo instrumento y evaluación independiente cuando el resultado depende del juicio. El Proyecto de Operaciones Unitarias es mi principal objeto de estudio desde 2017.' },
  'sotl.intro2':             { en: 'The most recent study follows 112 students across four cohorts (Acuña et al., 2025). Written communication improved with statistical significance under one-way ANOVA (F = 7.50, p < 0.001), and a blind evaluation by external readers confirmed it across six rubric criteria (p = 0.005 to 0.014). Technical performance held steady. Sustained motivation reached 94% of students against 67% under the previous model. Those numbers changed the course: the 50-50 structure now in place came out of what the analysis showed, not out of intuition.', es: 'El estudio más reciente sigue a 112 estudiantes a lo largo de cuatro cohortes (Acuña et al., 2025). La comunicación escrita mejoró con significancia estadística bajo ANOVA de una vía (F = 7,50, p < 0,001), y una evaluación ciega a cargo de lectores externos lo confirmó en seis criterios de la rúbrica (p = 0,005 a 0,014). El desempeño técnico se mantuvo estable. La motivación sostenida alcanzó al 94% de los estudiantes frente al 67% del modelo anterior. Esos números cambiaron el curso: la estructura 50-50 que hoy funciona salió de lo que mostró el análisis, no de la intuición.' },
  'sotl.intro3':             { en: 'The cycle has closed three times since 2019: measure the course, publish what the measurement shows, redesign on that basis, measure again. Each turn left a peer-reviewed paper in Education for Chemical Engineers, and the last one earned the 2026 AIChE Award for Innovation in Chemical Engineering Education. Serving as Subject Editor of that same journal puts me on the other side of the process, judging whether the evidence other academics present about their teaching holds up.', es: 'El ciclo se ha cerrado tres veces desde 2019: medir el curso, publicar lo que la medición muestra, rediseñar sobre esa base y volver a medir. Cada vuelta dejó un artículo arbitrado en Education for Chemical Engineers, y la última obtuvo el AIChE Award for Innovation in Chemical Engineering Education 2026. Ser Subject Editor de esa misma revista me pone del otro lado del proceso: juzgar si la evidencia que otros académicos presentan sobre su docencia se sostiene.' },
  'sotl.cycle.title':        { en: 'How the cycle closes', es: 'Cómo se cierra el ciclo' },
  'sotl.cycle.sub':          { en: 'The same loop has run three times since 2019. Each turn leaves a peer-reviewed paper and a course that changed because of what the paper found.', es: 'El mismo ciclo ha corrido tres veces desde 2019. Cada vuelta deja un artículo arbitrado y un curso que cambió por lo que ese artículo encontró.' },
  'sotl.cycle.s1':           { en: 'Measure',                es: 'Medir' },
  'sotl.cycle.s1d':          { en: 'A baseline before the intervention, one instrument across cohorts, and independent readers when the outcome depends on judgment.', es: 'Una línea base antes de la intervención, un mismo instrumento entre cohortes y lectores independientes cuando el resultado depende del juicio.' },
  'sotl.cycle.s2':           { en: 'Publish',                es: 'Publicar' },
  'sotl.cycle.s2d':          { en: 'The result goes to peer review. What survives review is a finding. What does not is an opinion about my own course.', es: 'El resultado va a revisión por pares. Lo que sobrevive a la revisión es un hallazgo. Lo que no, es una opinión sobre mi propio curso.' },
  'sotl.cycle.s3':           { en: 'Redesign',               es: 'Rediseñar' },
  'sotl.cycle.s3d':          { en: 'The course changes on the evidence, not on intuition. The next cohort meets a different course.', es: 'El curso cambia por la evidencia, no por intuición. La cohorte siguiente se encuentra con un curso distinto.' },
  'sotl.cycle.return':       { en: 'and that cohort becomes the next baseline', es: 'y esa cohorte se vuelve la nueva línea base' },
  'sotl.cycle.turns':        { en: 'Three completed turns', es: 'Tres vueltas completas' },
  'sotl.cycle.turn':         { en: 'Turn',                   es: 'Vuelta' },
  'sotl.turn1.change':       { en: 'A joint design project links Unit Operations with Modelling and Simulation.', es: 'Un proyecto de diseño conjunto une Operaciones Unitarias con Modelado y Simulación.' },
  'sotl.turn2.change':       { en: 'The course moves to a student-centred framework: flipped classroom, PO-PBL, interactive e-learning.', es: 'El curso pasa a un marco centrado en el estudiante: aula invertida, PO-PBL y e-learning interactivo.' },
  'sotl.turn3.change':       { en: 'Gamification, self- and peer-evaluation, and generative AI bounded by the AIAS enter the PO-PBL model.', es: 'La gamificación, la autoevaluación y coevaluación, y la IA generativa acotada por la AIAS entran al modelo PO-PBL.' },
  'sotl.turn3.outcome':      { en: 'Recognized with the 2026 AIChE Award for Innovation in Chemical Engineering Education.', es: 'Reconocido con el AIChE Award for Innovation in Chemical Engineering Education 2026.' },
  'sotl.case':               { en: 'The seven-year record of that study, phase by phase, with the evaluation series and the papers each phase produced:', es: 'El registro de siete años de ese estudio, fase por fase, con la serie de evaluaciones y los artículos que produjo cada fase:' },
  'sotl.caseCta':            { en: 'Unit Operations Innovation', es: 'Innovación en Operaciones Unitarias' },

  // Professional Development
  'profdev.title':           { en: 'Improving My Teaching Performance', es: 'Mejorando mi Desempeño Docente' },
  'profdev.sub':             { en: 'Since I arrived at the university, I have focused on improving and deepening my understanding of how to teach effectively and create lasting impact. For this reason, I have taken various workshops and courses to continually refine my pedagogical approach.', es: 'Desde que llegué a la universidad, me he enfocado en mejorar y profundizar mi comprensión sobre cómo enseñar de manera efectiva y generar un impacto duradero. Por esta razón, he tomado diversos talleres y cursos para refinar continuamente mi enfoque pedagógico.' },
} as const;
