export const teaching = {
  // Teaching Overview
  'teaching.overview.title':    { en: 'Teaching Overview',  es: 'Visión General de Docencia' },
  'teaching.overview.subtitle': { en: 'Fostering the next generation of innovators through project-based learning and real-world challenges.', es: 'Formando a la próxima generación de innovadores mediante aprendizaje basado en proyectos y retos del mundo real.' },
  'teaching.overview.approach.title': { en: 'My Teaching Approach', es: 'Mi Enfoque Pedagógico' },
  'teaching.overview.approach.text':  { en: 'My teaching portfolio reflects a deep commitment to engineering education across all levels, from core undergraduate courses to specialized graduate seminars and professional development programs. My courses are designed to be dynamic, hands-on learning environments where students tackle real-world challenges. I emphasize a project-based approach that not only builds strong technical foundations but also cultivates essential professional skills like critical thinking, teamwork, and communication. Through my involvement in curriculum design, continuing education, and corporate training, I strive to create impactful learning experiences that bridge the gap between academic theory and industry practice, empowering the next generation of engineers to innovate and lead.', es: 'Mi portafolio docente refleja un profundo compromiso con la educación en ingeniería en todos los niveles, desde cursos básicos de pregrado hasta seminarios especializados de posgrado y programas de desarrollo profesional. Mis cursos están diseñados como entornos de aprendizaje dinámicos y prácticos donde los estudiantes abordan desafíos del mundo real. Hago énfasis en un enfoque basado en proyectos que no solo construye fundamentos técnicos sólidos, sino que también cultiva habilidades profesionales esenciales como el pensamiento crítico, el trabajo en equipo y la comunicación. A través de mi participación en el diseño curricular, la educación continua y la formación corporativa, me esfuerzo por crear experiencias de aprendizaje que cierren la brecha entre la teoría académica y la práctica industrial, empoderando a la próxima generación de ingenieros para innovar y liderar.' },

  // Courses
  'courses.title':           { en: 'Courses Taught',         es: 'Cursos Impartidos' },
  'courses.sub':             { en: 'Below is a comprehensive list of courses I have taught since 2017, detailing student engagement, course type, and my role in their design.', es: 'A continuación se presenta una lista completa de los cursos que he impartido desde 2017, con detalle de la participación estudiantil, el tipo de curso y mi rol en su diseño.' },
  'courses.col.term':        { en: 'Term',                   es: 'Período' },
  'courses.col.course':      { en: 'Course',                 es: 'Curso' },
  'courses.col.students':    { en: 'Students',               es: 'Estudiantes' },
  'courses.col.type':        { en: 'Type',                   es: 'Tipo' },
  'courses.col.evaluation':  { en: 'Student Evaluation',     es: 'Evaluación Estudiantil' },
  'courses.filter.all':         { en: 'All',           es: 'Todos' },
  'courses.filter.core':        { en: 'Core',          es: 'Obligatorio' },
  'courses.filter.elective':    { en: 'Elective',      es: 'Electivo' },
  'courses.filter.cbu':         { en: 'CBU',           es: 'CBU' },
  'courses.filter.undergraduate': { en: 'Undergraduate', es: 'Pregrado' },
  'courses.filter.graduate':    { en: 'Graduate',      es: 'Posgrado' },

  // Unit Ops Innovation
  'unitops.title':           { en: 'Unit Operations Innovation', es: 'Innovación en Operaciones Unitarias' },
  'unitops.sub':             { en: 'A Seven-Year Journey: From Theory and Problem-Sets to Project-Based Synthesis.', es: 'Un recorrido de siete años: de la teoría y los ejercicios al aprendizaje basado en proyectos.' },
  'unitops.context':         { en: 'Context',                es: 'Contexto' },
  'unitops.evolution':       { en: 'The Evolution',          es: 'La Evolución' },
  'unitops.impact':          { en: 'Impact on Student Experience', es: 'Impacto en la Experiencia Estudiantil' },
  'unitops.lessons':         { en: 'Lessons Learned',        es: 'Lecciones Aprendidas' },
  'unitops.scholarly':       { en: 'Scholarly Foundation',   es: 'Base Académica' },
  'unitops.chart.title':     { en: 'Score Evolution: The Reform Journey', es: 'Evolución de Puntajes: El Camino de la Reforma' },
  'unitops.chart.scale':     { en: 'Institutional 100–200 Scale', es: 'Escala Institucional 100–200' },
  'unitops.phase.traditional': { en: 'Traditional',         es: 'Tradicional' },
  'unitops.phase.reform':    { en: 'Reform Era',             es: 'Era de Reforma' },
  'unitops.phase.synthesis': { en: 'Synthesis',              es: 'Síntesis' },
  'unitops.quote':           { en: '"The result speaks for itself. The course now combines the rigor students expect with the authentic design experience that motivated the original transformation."', es: '«El resultado habla por sí solo. El curso ahora combina el rigor que los estudiantes esperan con la experiencia auténtica de diseño que motivó la transformación original.»' },
  'unitops.context.text1':   { en: 'Unit Operations is the foundational course in chemical engineering curricula worldwide. In 2021, following a mandate from the ', es: 'Operaciones Unitarias es el curso fundamental en los planes de estudio de ingeniería química en todo el mundo. En 2021, tras un mandato de la ' },
  'unitops.context.school':  { en: 'School of Engineering', es: 'Facultad de Ingeniería' },
  'unitops.context.text2':   { en: ' for greater experiential learning, the ', es: ' para incorporar más aprendizaje experiencial, el ' },
  'unitops.context.dept':    { en: 'Department of Chemical and Food Engineering', es: 'Departamento de Ingeniería Química y de Alimentos' },
  'unitops.context.text3':   { en: ' undertook a comprehensive curriculum reform. This documentation chronicles the transformation of Unit Operations under that reform, the challenges encountered, and the pedagogical synthesis that eventually emerged.', es: ' emprendió una reforma curricular integral. Esta documentación narra la transformación de Operaciones Unitarias bajo esa reforma, los desafíos enfrentados y la síntesis pedagógica que finalmente surgió.' },
  'unitops.phase1.title':    { en: 'Phase 1: Traditional Approach (2017–2021)', es: 'Fase 1: Enfoque Tradicional (2017–2021)' },
  'unitops.phase1.tag':      { en: 'Stable',                 es: 'Estable' },
  'unitops.phase1.text':     { en: 'The original course followed the standard model: comprehensive lectures covering theoretical foundations, worked examples, and traditional homework assignments. Evaluations were stable, averaging 153.9. While effective, the format offered limited opportunity for students to integrate concepts through authentic engineering problems.', es: 'El curso original seguía el modelo estándar: clases magistrales completas que cubrían los fundamentos teóricos, ejemplos resueltos y tareas tradicionales. Las evaluaciones eran estables, con un promedio de 153,9. Aunque efectivo, el formato ofrecía pocas oportunidades para que los estudiantes integraran conceptos mediante problemas auténticos de ingeniería.' },
  'unitops.phase2.title':    { en: 'Phase 2: Curriculum Reform and PO-PBL (2021–2023)', es: 'Fase 2: Reforma Curricular y PO-PBL (2021–2023)' },
  'unitops.phase2.tag':      { en: 'Declined',               es: 'En Declive' },
  'unitops.phase2.text1':    { en: 'The course became {ip2} under a pure Project-Oriented Problem-Based Learning format. Theory was minimized as students learned through semester-long design projects.', es: 'El curso se convirtió en {ip2} bajo un formato puro de Aprendizaje Basado en Problemas Orientado a Proyectos. La teoría se minimizó a medida que los estudiantes aprendían mediante proyectos de diseño a lo largo del semestre.' },
  'unitops.phase2.ip2':      { en: 'Integrated Project 2',   es: 'Proyecto Integrador 2' },
  'unitops.phase2.text2pre': { en: 'The magnitude of change was severe. Student response was challenging; evaluations dropped sharply to a ', es: 'La magnitud del cambio fue severa. La respuesta de los estudiantes fue difícil; las evaluaciones cayeron bruscamente hasta un ' },
  'unitops.phase2.text2low': { en: 'low of 135 in 2022-20',  es: 'mínimo de 135 en 2022-20' },
  'unitops.phase2.text2post':{ en: '. Students expressed frustration with the cognitive load of learning new concepts while simultaneously applying them without structured theoretical guidance.', es: '. Los estudiantes expresaron frustración por la carga cognitiva de aprender conceptos nuevos y aplicarlos simultáneamente sin una guía teórica estructurada.' },
  'unitops.phase3.title':    { en: 'Phase 3: Finding the Balance (2024–Present)', es: 'Fase 3: Encontrando el Equilibrio (2024–Presente)' },
  'unitops.phase3.tag':      { en: 'Recovered',              es: 'Recuperado' },
  'unitops.phase3.text1':    { en: 'The transition to Unit Operations Project in 2024 marked a new synthesis. I integrated ', es: 'La transición a Proyecto de Operaciones Unitarias en 2024 marcó una nueva síntesis. Integré ' },
  'unitops.phase3.genai':    { en: 'Generative AI',          es: 'IA Generativa' },
  'unitops.phase3.text2':    { en: ' tools and added theoretical content back. The final breakthrough came in 2025-20 with a deliberate ', es: ' y volví a añadir contenido teórico. El avance definitivo llegó en 2025-20 con una estructura deliberada ' },
  'unitops.phase3.fifty':    { en: '50-50 structure',        es: '50-50' },
  'unitops.phase3.text3':    { en: ': half dedicated to theory and problem-solving, and half to a semester-long ', es: ': la mitad dedicada a la teoría y la resolución de problemas, y la mitad a un proyecto de diseño ' },
  'unitops.phase3.insilico': { en: 'in silico',              es: 'in silico' },
  'unitops.phase3.text4':    { en: ' design project using ',   es: ' a lo largo del semestre usando ' },
  'unitops.phase3.aspen':    { en: 'ASPEN simulation',       es: 'simulación en ASPEN' },
  'unitops.phase3.text5':    { en: '. Evaluations recovered to ', es: '. Las evaluaciones se recuperaron hasta ' },
  'unitops.phase3.text6':    { en: ', matching institutional benchmarks.', es: ', igualando los referentes institucionales.' },
  'unitops.chart.note':      { en: "Note: Pandora's Laboratory maintained a consistent 157.6 average as a reference benchmark across the same period.", es: 'Nota: el Laboratorio de Pandora mantuvo un promedio constante de 157,6 como referente durante el mismo período.' },
  'unitops.chart.benchmark': { en: 'Ref Benchmark (157.6)',  es: 'Referente (157,6)' },
  'unitops.lesson1.title':   { en: 'Theoretical Foundations', es: 'Fundamentos Teóricos' },
  'unitops.lesson1.desc':    { en: 'Even in project-based contexts, students value theoretical frameworks. Explicit instruction provides the scaffolding needed to tackle complex problems confidently.', es: 'Incluso en contextos basados en proyectos, los estudiantes valoran los marcos teóricos. La instrucción explícita brinda el andamiaje necesario para abordar problemas complejos con confianza.' },
  'unitops.lesson2.title':   { en: 'Iterative Refinement',   es: 'Refinamiento Iterativo' },
  'unitops.lesson2.desc':    { en: 'Pedagogical innovation requires sustaining and documenting each phase. The evaluation recovery from 135 to 156 occurred over six semesters of sustainment.', es: 'La innovación pedagógica requiere sostener y documentar cada fase. La recuperación de las evaluaciones de 135 a 156 ocurrió a lo largo de seis semestres de sostenimiento.' },
  'unitops.lesson3.title':   { en: 'In Silico Bridging',     es: 'Puente In Silico' },
  'unitops.lesson3.desc':    { en: 'ASPEN simulation addresses physical laboratory constraints, allowing students to see immediate consequences of engineering decisions in larger scopes.', es: 'La simulación en ASPEN aborda las limitaciones del laboratorio físico, permitiendo a los estudiantes ver las consecuencias inmediatas de las decisiones de ingeniería en escalas mayores.' },
  'unitops.lesson4.title':   { en: 'AI-Assisted Rigor',      es: 'Rigor Asistido por IA' },
  'unitops.lesson4.desc':    { en: 'GenAI tools support learning when properly scaffolded. Structured AI integration (AIAS framework) improved literature review quality while maintaining rigor.', es: 'Las herramientas de IA generativa apoyan el aprendizaje cuando se andamian adecuadamente. La integración estructurada de IA (marco AIAS) mejoró la calidad de las revisiones de literatura manteniendo el rigor.' },

  // Continuing Education
  'contEd.title':            { en: 'Continuing Education',   es: 'Educación Continua' },
  'contEd.sub':              { en: 'Beyond traditional university courses, I am actively involved in designing and delivering continuing education programs and corporate training. These courses aim to bridge the gap between academia and industry, providing professionals with cutting-edge skills in areas like artificial intelligence, biotechnology, and innovation management.', es: 'Más allá de los cursos universitarios tradicionales, participo activamente en el diseño y la impartición de programas de educación continua y formación corporativa. Estos cursos buscan cerrar la brecha entre la academia y la industria, dotando a los profesionales de habilidades de vanguardia en áreas como inteligencia artificial, biotecnología y gestión de la innovación.' },
  'contEd.col.year':         { en: 'Year',                   es: 'Año' },
  'contEd.col.title':        { en: 'Course Title',           es: 'Título del Curso' },
  'contEd.col.type':         { en: 'Type / Client',          es: 'Tipo / Cliente' },
  'contEd.col.attendees':    { en: 'Attendees',              es: 'Participantes' },
  'contEd.col.role':         { en: 'Role',                   es: 'Rol' },
  'contEd.filter.all':         { en: 'All',              es: 'Todos' },
  'contEd.filter.open':        { en: 'Open Course',      es: 'Curso Abierto' },
  'contEd.filter.corporate':   { en: 'Corporate Course', es: 'Curso Corporativo' },
  'contEd.filter.summer':      { en: 'Summer School',    es: 'Escuela de Verano' },

  // Testimonials
  'testimonials.title':      { en: 'Student Testimonials',   es: 'Testimonios de Estudiantes' },
  'testimonials.sub':        { en: 'Hearing from students is the most meaningful measure of teaching success. Here is what some of my past and present students have to say about their learning experiences.', es: 'Escuchar a los estudiantes es la medida más significativa del éxito docente. Esto es lo que algunos de mis estudiantes, pasados y presentes, tienen que decir sobre sus experiencias de aprendizaje.' },
  'testimonials.filter.all': { en: 'All',                    es: 'Todos' },
  'testimonials.filter.teaching': { en: 'Teaching & Mentorship', es: 'Docencia y Mentoría' },
  'testimonials.filter.research': { en: 'Research Advising', es: 'Asesoría de Investigación' },

  // Scholarship of Teaching
  'sotl.title':              { en: 'Scholarship of Teaching & Learning (SOTL)', es: 'Investigación sobre la Enseñanza y el Aprendizaje (SoTL)' },
  'sotl.sub':                { en: 'Applying rigorous research skills to improve pedagogical practices in engineering, enhancing student learning and professional development.', es: 'Aplicando habilidades de investigación rigurosa para mejorar las prácticas pedagógicas en ingeniería, mejorando el aprendizaje estudiantil y el desarrollo profesional.' },
  'sotl.editorial':          { en: 'Editorial Contributions', es: 'Contribuciones Editoriales' },
  'sotl.publications':       { en: 'Related Publications',   es: 'Publicaciones Relacionadas' },
  'sotl.visitJournal':       { en: 'Visit Journal',          es: 'Visitar Revista' },
  'sotl.readMore':           { en: 'Read More →',            es: 'Leer más →' },
  'sotl.intro1':             { en: 'My commitment to education extends beyond the classroom into the systematic study of teaching and learning itself. I am an active participant in the Scholarship of Teaching and Learning (SOTL) community, where I apply my research skills to improve pedagogical practices in engineering.', es: 'Mi compromiso con la educación se extiende más allá del aula hacia el estudio sistemático de la enseñanza y el aprendizaje mismos. Soy participante activo de la comunidad de Investigación sobre la Enseñanza y el Aprendizaje (SoTL), donde aplico mis habilidades de investigación para mejorar las prácticas pedagógicas en ingeniería.' },
  'sotl.intro2':             { en: 'This work involves designing, implementing, and rigorously assessing innovative teaching strategies to enhance student learning and professional development. My SOTL research often focuses on integrating real-world industry challenges into the curriculum, fostering essential skills like teamwork and creativity, and leveraging new technologies to create more engaging and effective learning environments. Below are some of the products of this research.', es: 'Este trabajo implica diseñar, implementar y evaluar con rigor estrategias docentes innovadoras para mejorar el aprendizaje estudiantil y el desarrollo profesional. Mi investigación en SoTL suele enfocarse en integrar retos reales de la industria en el currículo, fomentar habilidades esenciales como el trabajo en equipo y la creatividad, y aprovechar nuevas tecnologías para crear entornos de aprendizaje más atractivos y efectivos. A continuación se presentan algunos de los productos de esta investigación.' },

  // Professional Development
  'profdev.title':           { en: 'Improving My Teaching Performance', es: 'Mejorando mi Desempeño Docente' },
  'profdev.sub':             { en: 'Since I arrived at the university, I have focused on improving and deepening my understanding of how to teach effectively and create lasting impact. For this reason, I have taken various workshops and courses to continually refine my pedagogical approach.', es: 'Desde que llegué a la universidad, me he enfocado en mejorar y profundizar mi comprensión sobre cómo enseñar de manera efectiva y generar un impacto duradero. Por esta razón, he tomado diversos talleres y cursos para refinar continuamente mi enfoque pedagógico.' },
} as const;
