import type { Grant } from '../../types';

export const grantsData: Grant[] = [
  {
    title: 'Comparative evaluation of feedback generated by AI and by inter-institutional professors in STEM courses: impact on conceptual learning and student perception',
    startYear: 2025,
    endYear: 2027,
    organization: 'NOVUS Tríada 2025 (Pontificia Universidad Católica de Chile, Instituto Tecnológico y de Estudios Superiores de Monterrey, Universidad de los Andes)',
    role: { en: 'Lead investigator for Universidad de los Andes', es: 'Responsable por la Universidad de los Andes' },
    status: 'In Progress',
    area: 'education'
  },
  {
    title: 'Environmental Mitigation, H2S Corrosion and Science Communication at the Paraíso Hydroelectric Power Plant: Phase 3 (Life Cycle Analysis, Risk Management and Aspen Plus Process Modeling), Evaluation of the Incidence of Hydrogen Sulfide on Atmospheric Corrosion in Metallic Materials, and Informational Material on H2S',
    startYear: 2025,
    endYear: 2027,
    organization: 'Enel Colombia S.A. E.S.P.',
    role: { en: 'Principal Investigator', es: 'Investigador principal' },
    status: 'In Progress'
  },
  {
    title: 'Generative AI Literacy at Universidad de los Andes, Beyond the Tools: A Multiple Case Study',
    startYear: 2025,
    endYear: 2026,
    organization: 'Universidad de los Andes (Horizontes Conectados)',
    role: { en: 'Co-investigator', es: 'Coinvestigador' },
    status: 'In Progress',
    area: 'education'
  },
  {
    title: 'Phase 2: Mitigation of Environmental and Social Impacts at the Paraíso Power Plant Arising from the Polluted Conditions of the Bogotá River, and Analysis of Hydrogen Sulfide Concentrations: Influence of Operational and Environmental Factors',
    startYear: 2024,
    endYear: 2025,
    organization: 'Enel Colombia S.A. E.S.P.',
    role: { en: 'Principal Investigator', es: 'Investigador principal' },
    status: 'Concluded'
  },
  {
    title: 'Valorization of Glycerol in the Production of 1,3-Propanediol',
    startYear: 2024,
    endYear: 2024,
    organization: 'Bio D S.A.',
    role: { en: 'Principal Investigator', es: 'Investigador principal' },
    status: 'Concluded'
  },
  {
    title: 'Development of a High-Protein Peanut Butter Food Product',
    startYear: 2024,
    endYear: 2024,
    organization: 'Akicorp Engineering',
    role: { en: 'Co-Principal Investigator (with Andrea del Pilar Sánchez Camargo)', es: 'Coinvestigador principal (con Andrea del Pilar Sánchez Camargo)' },
    status: 'Concluded'
  },
  {
    title: 'Phase 1 - Part 1: Diagnosis and Modeling of the Ecofilter System of the Paraíso Power Plant for the Removal of Offensive Odors',
    startYear: 2023,
    endYear: 2024,
    organization: 'Enel Colombia S.A. E.S.P.',
    role: { en: 'Principal Investigator', es: 'Investigador principal' },
    status: 'Concluded'
  },
  {
    title: 'Technological Strategies for Odor Control',
    startYear: 2022,
    endYear: 2022,
    organization: 'Enel Colombia S.A. E.S.P.',
    role: { en: 'Principal Investigator', es: 'Investigador principal' },
    status: 'Concluded'
  },
  {
    title: 'Validation of Plant Layout Design and Advisory in Equipment Selection for the Expansion of Technifarm',
    startYear: 2022,
    endYear: 2022,
    organization: 'Technifarm',
    role: { en: 'Co-investigator', es: 'Coinvestigador' },
    status: 'Concluded'
  },
  {
    title: 'Hybrid Biotransformation Process of Surgical Masks using TiO2 Nanoparticles and Microcosms',
    startYear: 2020,
    endYear: 2023,
    organization: 'Universidad de los Andes, Pontificia Universidad Javeriana and Universidad del Rosario',
    role: { en: 'Co-investigator', es: 'Coinvestigador' },
    status: 'Concluded'
  },
  {
    title: 'Study of new translocating peptides derived from SARS-CoV-2: a bioinformatic study',
    startYear: 2020,
    endYear: 2021,
    organization: 'Rescale: Tech Against COVID',
    role: { en: 'Co-Principal Investigator', es: 'Coinvestigador principal' },
    status: 'Concluded'
  },
  {
    title: 'Modular bioreactor with interchangeable parts',
    startYear: 2020,
    organization: 'Minciencias',
    role: { en: 'Inventor', es: 'Inventor' },
    status: 'Concluded'
  },
  {
    title: 'Production of recombinant antimicrobial peptides for the modification of materials of biomedical interest',
    startYear: 2020,
    endYear: 2022,
    organization: 'Fundación Santa Fe de Bogotá (FSFB) and Universidad de los Andes, 2019 joint call',
    role: { en: 'Principal Investigator', es: 'Investigador principal' },
    status: 'Concluded'
  },
  {
    title: 'New antimicrobial and cell penetration systems: molecules with membrane activity from libraries screened in high-performance on-a-chip systems',
    startYear: 2019,
    endYear: 2023,
    organization: 'Departamento Administrativo de Ciencia, Tecnología e Innovación (Colciencias, now Minciencias), Call 844 of 2019',
    role: { en: 'Principal Investigator', es: 'Investigador principal' },
    status: 'Concluded'
  },
  {
    title: 'Evaluation of gene therapies for the treatment of Parkinson’s disease using nanostructured vehicles and CRISPR/Cas9',
    startYear: 2019,
    endYear: 2023,
    organization: 'Departamento Administrativo de Ciencia, Tecnología e Innovación (Colciencias, now Minciencias), Call 844 of 2019',
    role: { en: 'Co-investigator', es: 'Coinvestigador' },
    status: 'Concluded'
  },
  {
    title: 'Improvement in the functional screening of metagenomic libraries. Research plan. Research support program for assistant professors (FAPA)',
    startYear: 2019,
    endYear: 2021,
    organization: 'Vicerrectoría de Investigaciones Uniandes',
    role: { en: 'Principal Investigator', es: 'Investigador principal' },
    status: 'Concluded'
  },
  {
    title: 'Gene therapy for inborn errors of metabolism using CRISPR/Cas9 and a delivery system based on magnetoliposomes',
    startYear: 2019,
    endYear: 2022,
    organization: 'Departamento Administrativo de Ciencia, Tecnología e Innovación (Colciencias, now Minciencias), Call 807 of 2018, with the Pontificia Universidad Javeriana',
    role: { en: 'Co-investigator (Uniandes’ PI)', es: 'Coinvestigador (IP por Uniandes)' },
    status: 'Concluded'
  },
  {
    title: 'Pumping optimization to the Muña Reservoir and obstruction reduction of the loading pipeline at the Charquito Power Plant',
    startYear: 2018,
    endYear: 2019,
    organization: 'Emgesa S.A. E.S.P. (now Enel Colombia S.A. E.S.P.)',
    role: { en: 'Co-investigator', es: 'Coinvestigador' },
    status: 'Concluded'
  }
];