import type { Grant } from '../../types';

export const grantsData: Grant[] = [
  {
    title: 'Comparative evaluation of feedback generated by AI and by inter-institutional professors in STEM courses: impact on conceptual learning and student perception',
    startYear: 2025,
    endYear: 2027,
    organization: 'Novus Triada 2025',
    role: 'Co-investigator',
    status: 'In Progress'
  },
  {
    title: 'Development of Informational Material on H2S for the Paraíso Hydroelectric Power Plant',
    startYear: 2025,
    endYear: 2025,
    organization: 'ENEL S.A.',
    role: 'Principal Investigator',
    status: 'In Progress'
  },
  {
    title: 'Evaluation of the Incidence of Hydrogen Sulfide on Atmospheric Corrosion in Metallic Materials in the Area of Influence of the Paraíso Hydroelectric Power Plant',
    startYear: 2025,
    endYear: 2026,
    organization: 'ENEL S.A.',
    role: 'Principal Investigator',
    status: 'In Progress'
  },
  {
    title: 'Phase 1 - Part 3: Diagnosis and Modeling of the Ecofilter System of the Paraíso Power Plant for the Removal of Offensive Odors',
    startYear: 2025,
    endYear: 2026,
    organization: 'ENEL S.A.',
    role: 'Principal Investigator',
    status: 'In Progress'
  },
  {
    title: 'Generative AI Literacy at Universidad de los Andes, Beyond the Tools: A Multiple Case Study',
    startYear: 2025,
    endYear: 2026,
    organization: 'Universidad de los Andes (Horizontes Conectados)',
    role: 'Co-investigator',
    status: 'In Progress'
  },
  {
    title: 'Phase 1 - Part 2: Diagnosis and Modeling of the Ecofilter System of the Paraíso Power Plant for the Removal of Offensive Odors',
    startYear: 2024,
    endYear: 2025,
    organization: 'ENEL S.A.',
    role: 'Principal Investigator',
    status: 'Concluded'
  },
  {
    title: 'Phase 1 - Part 1: Diagnosis and Modeling of the Ecofilter System of the Paraíso Power Plant for the Removal of Offensive Odors',
    startYear: 2023,
    endYear: 2024,
    organization: 'ENEL S.A.',
    role: 'Principal Investigator',
    status: 'Concluded'
  },
  {
    title: 'Technological Strategies for Odor Control',
    startYear: 2022,
    endYear: 2022,
    organization: 'ENEL S.A.',
    role: 'Principal Investigator',
    status: 'Concluded'
  },
  {
    title: 'Validation of Plant Layout Design and Advisory in Equipment Selection for the Expansion of Technifarm',
    startYear: 2022,
    endYear: 2022,
    organization: 'Technifarm',
    role: 'Co-investigator',
    status: 'Concluded'
  },
  {
    title: 'Hybrid Biotransformation Process of Surgical Masks using TiO2 Nanoparticles and Microcosms',
    startYear: 2020,
    endYear: 2023,
    organization: 'Uniandes, Pontificia Universidad Javeriana, Universidad del Rosario',
    role: 'Co-investigator',
    status: 'Concluded'
  },
  {
    title: 'Study of new translocating peptides derived from SARS-CoV-2: a bioinformatic study',
    startYear: 2020,
    endYear: 2021,
    organization: 'Rescale: Tech Against COVID',
    role: 'Co-Principal Investigator',
    status: 'Concluded'
  },
  {
    title: 'Modular bioreactor with interchangeable parts',
    startYear: 2020,
    organization: 'Minciencias',
    role: 'Inventor',
    status: 'Concluded'
  },
  {
    title: 'Production of recombinant antimicrobial peptides for the modification of materials of biomedical interest',
    startYear: 2019,
    endYear: 2021,
    organization: 'Joint investigation - FSFB (Fundación Santa Fé de Bogotá) / Uniandes',
    role: 'Principal Investigator',
    status: 'Concluded'
  },
  {
    title: 'New antimicrobial and cell penetration systems: molecules with membrane activity from libraries screened in high-performance on-a-chip systems',
    startYear: 2019,
    endYear: 2023,
    organization: 'Minciencias',
    role: 'Principal Investigator',
    status: 'Concluded'
  },
  {
    title: 'Evaluation of gene therapies for the treatment of Parkinson’s disease using nanostructured vehicles and CRISPR/Cas9',
    startYear: 2019,
    endYear: 2023,
    organization: 'Minciencias',
    role: 'Co-investigator',
    status: 'Concluded'
  },
  {
    title: 'Improvement in the functional screening of metagenomic libraries. Research plan. Research support program for assistant professors (FAPA)',
    startYear: 2019,
    endYear: 2021,
    organization: 'Vicerrectoría de Investigaciones Uniandes',
    role: 'Principal Investigator',
    status: 'Concluded'
  },
  {
    title: 'Gene therapy for inborn errors of metabolism using CRISPR/Cas9 and a delivery system based on magnetoliposomes',
    startYear: 2018,
    endYear: 2021,
    organization: 'Minciencias',
    role: 'Co-investigator (Uniandes’ PI)',
    status: 'Concluded'
  },
  {
    title: 'Pumping optimization to the Muña Reservoir and obstruction reduction of the loading pipeline at the Charquito Power Plant',
    startYear: 2018,
    endYear: 2019,
    organization: 'ENEL-Emgesa',
    role: 'Co-investigator',
    status: 'Concluded'
  }
];